<template>
<section class="section-content">
    <div class="content-header">
        <a-page-header style="border: 1px solid rgb(235, 237, 240);" title="Tableau de bord" />
    </div>
    <div class="container mn-10">
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat eaque
        nostrum libero, eius quae voluptate rem eum itaque provident, aspernatur,
        facilis neque ducimus ea architecto mollitia est quis tempore! Dicta?
    </div>
</section>
</template>

<script>
export default {};
</script>

<style>
</style>
